# See config.example.yml for documentation.
object_base: orig/RO3EXJ
object: sys/main.dol
hash: 07ffee3033bb1784c0da378f8034271ef43e7c28
symbols: config/RO3EXJ/symbols.txt
splits: config/RO3EXJ/splits.txt
